# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QLearn
                                 A QGIS plugin
 QLearn preforms automatic training of a neural network model on raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-01
        copyright            : (C) 2025 by Adam Bialecki
        email                : adam@ardanika.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Adam Bialecki'
__date__ = '2025-02-01'
__copyright__ = '(C) 2025 by Adam Bialecki'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QLearn class from file QLearn.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .QLearn import QLearnPlugin
    return QLearnPlugin()
