# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QLearn
                                 A QGIS plugin
 QLearn preforms automatic training of a neural network model on raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-01
        copyright            : (C) 2025 by Adam Bialecki
        email                : adam@ardanika.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Adam Bialecki'
__date__ = '2025-02-01'
__copyright__ = '(C) 2025 by Adam Bialecki'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (Qgis,
                       QgsProcessing,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterMultipleLayers,
                       QgsProcessingParameterFileDestination,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterNumber)

from .QLearnDataset import QDataset
from .QLearnTrain import QUNetTrainer
import torch
import traceback


class QLearnTrainingAlgorithm(QgsProcessingAlgorithm):
    
    def flags(self):
        return super().flags() #| Qgis.ProcessingAlgorithmFlag.NoThreading
    
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT_MODEL = 'OUTPUT_MODEL'
    INPUT_TRAIN = 'INPUT_TRAINING_RASTER'
    INPUT_TARGET = 'INPUT_TARGET_RASTER'
    ARGS_NODATA = 'ARGS_NODATA'
    ARGS_EPOCHS = 'ARGS_EPOCH'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Input Training Rasters
        self.addParameter(
            QgsProcessingParameterMultipleLayers(
            self.INPUT_TRAIN,
            self.tr("Input rasters"),
            layerType=QgsProcessing.SourceType.TypeRaster)
        )

        # Input Target Rasters
        self.addParameter(
            QgsProcessingParameterMultipleLayers(
            self.INPUT_TARGET,
            self.tr("Target raster"),
            layerType=QgsProcessing.SourceType.TypeRaster)
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.ARGS_EPOCHS,
                self.tr("Number of Epochs"),
                defaultValue=10
            )
        )

        self.addParameter(
            QgsProcessingParameterNumber(
                self.ARGS_NODATA,
                self.tr("NODATA Value"),
                defaultValue=0
            )
        )

        self.addParameter(
            QgsProcessingParameterFileDestination(
                self.OUTPUT_MODEL,
                self.tr("Output model location"),
                fileFilter='PyTorch Model(*.pth)'
            )
        )


    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Fetch Input Parameters from Dict
        training_rasters = self.parameterAsLayerList(parameters, self.INPUT_TRAIN, context)
        target_rasters = self.parameterAsLayerList(parameters, self.INPUT_TARGET, context)
        model_save_loc = self.parameterAsFileOutput(parameters, self.OUTPUT_MODEL, context)
        n_epochs = self.parameterAsInt(parameters,self.ARGS_EPOCHS, context)
        nodata = self.parameterAsInt(parameters,self.ARGS_NODATA, context)

        args = {
            "CHUNK_SIZE": 256,
            "NODATA": nodata,
            "IGNORE_INDEX" : -100,
            "BANDS": 8,
            "BATCH_SIZE": 16,
            "LEARNING_RATE": 1e-3,
            "EPOCHS": n_epochs,
            "DEVICE": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
            "TRAIN_TYPE": "classification", # classification or regression
            "GENERATE_AUGMENTED": False,
            "NORMALIZE": False,
            "CLASS_REMAPPING": True
        }

        feedback.pushInfo(f"Args: {args}")

        # Setup Dataset
        dataset = QDataset(training_rasters, target_rasters,context,feedback,args)
        trainer = QUNetTrainer(dataset,model_save_loc,feedback,args)
        try:
            trainer.train()
        except Exception as e:
            feedback.reportError(str(e))
            raise e



        return {self.OUTPUT_MODEL: model_save_loc}


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'QLearnTrain'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Training'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return QLearnTrainingAlgorithm()
