# -*- coding: utf-8 -*-

"""
/***************************************************************************
 QLearn
                                 A QGIS plugin
 QLearn preforms automatic training of a neural network model on raster data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-02-01
        copyright            : (C) 2025 by Adam Bialecki
        email                : adam@ardanika.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Adam Bialecki'
__date__ = '2025-02-01'
__copyright__ = '(C) 2025 by Adam Bialecki'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,
                       QgsProcessingParameterRasterLayer,
                       QgsProcessingParameterRasterDestination,
                       QgsProcessingParameterMultipleLayers)

from qgis.analysis import (QgsAlignRaster)


class QLearnAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT_TRAIN = 'OUTPUT_TRAINING_RASTER'
    OUTPUT_TARGET = 'OUTPUT_TARGET_RASTER'
    INPUT_TRAIN = 'INPUT_TRAINING_RASTER'
    INPUT_TARGET = 'INPUT_TARGET_RASTER'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # Input Training Raster
        self.addParameter(
            QgsProcessingParameterRasterLayer(
            self.INPUT_TRAIN,
            self.tr("Input raster"))
        )

        # Input Target Raster
        self.addParameter(
            QgsProcessingParameterRasterLayer(
            self.INPUT_TARGET,
            self.tr("Target raster"))
        )

        # Output Preprocessed Raster
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT_TRAIN,
                self.tr('Output layer'),
                defaultValue="aligned_train.tif"
            )
        )

        # Output Preprocessed Raster
        self.addParameter(
            QgsProcessingParameterRasterDestination(
                self.OUTPUT_TARGET,
                self.tr('Output layer'),
                defaultValue="aligned_target.tif"
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        # Suggested Arguments:
        # AlignToCellsize smallest/largest

        feedback.pushInfo("Fetching Parameters...")
        training_raster = self.parameterAsRasterLayer(parameters, self.INPUT_TRAIN, context)
        target_raster = self.parameterAsRasterLayer(parameters, self.INPUT_TARGET, context)
        output_training = self.parameterAsOutputLayer(parameters, self.OUTPUT_TRAIN, context)
        output_target = self.parameterAsOutputLayer(parameters, self.OUTPUT_TARGET, context)
        
        feedback.pushInfo("Processing Rasters...")

        for ras in [training_raster, target_raster]:
            feedback.pushInfo(f"CRS: {ras.crs()}")
            feedback.pushInfo(f"Extent: {ras.extent()}")
            feedback.pushInfo(f"Valid: {ras.isValid()}")
            feedback.pushInfo(f"Source: {ras.source()}")
            feedback.pushInfo(f"Width: {ras.width()}")
            feedback.pushInfo(f"Height: {ras.height()}")
            feedback.pushInfo(f"Cellsize: {ras.rasterUnitsPerPixelX()},{ras.rasterUnitsPerPixelY}")
        
        
        # Setup Raster Alignment
        alignRaster = QgsAlignRaster()
        
        rasters_to_align = [
            QgsAlignRaster.Item(target_raster.source(),output_target),
            QgsAlignRaster.Item(training_raster.source(),output_training)
            ]

        alignRaster.setRasters(rasters_to_align)
        idx = alignRaster.suggestedReferenceLayer()
        if(idx is -1):
            feedback.pushInfo("Error: Raster Alignment Error")
            feedback.pushInfo(alignRaster.errorMessage())
            return {}
        print(f"Suggested Raster: {rasters_to_align[idx].inputFilename}")
        
        alignRaster.setParametersFromRaster(QgsAlignRaster.RasterInfo(training_raster.source()))

        success = alignRaster.checkInputParameters()
        if(not success):
            feedback.pushInfo("Error: Raster Alignment Error")
            feedback.pushInfo(alignRaster.errorMessage())
            return {}
        
        # Debug
        feedback.pushInfo(f"Extent: {alignRaster.alignedRasterExtent()}")
        feedback.pushInfo(f"Size: {alignRaster.alignedRasterSize()}")
        feedback.pushInfo(f"Cellsize: {alignRaster.cellSize()}")
        feedback.pushInfo(f"Clip Extent: {alignRaster.clipExtent()}")
        feedback.pushInfo(f"Rasters to Align: {alignRaster.rasters()}")
        feedback.pushInfo(f"Destination CRS: {alignRaster.destinationCrs()}")

        success = alignRaster.run()
        if(not success):
            feedback.pushInfo("Error: Raster Alignment Error")
            feedback.pushInfo(alignRaster.errorMessage())
            return {}
        
        feedback.pushInfo(f"Alignment successful!")

        return {self.OUTPUT_TARGET: output_target, self.OUTPUT_TRAIN: output_training}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'QLearnTrain'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Training Neural Network Model'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return QLearnAlgorithm()
